Add support for Python 3.12
apify/apify-actor-docker pull request #112
Opened 2023-10-17 13:05 UTC by vdusek

Closes https://github.com/apify/apify-core/issues/12587

2023-10-17 14:58 UTC, vdusek commented
In the case of Playwright, blocked until [v1.39.0](https://github.com/microsoft/playwright-python/releases/tag/v1.39.0) is not released on PyPI.

2023-10-17 15:03 UTC, vdusek commented
Blocked by https://github.com/apify/apify-actor-docker/issues/113

2023-10-18 14:08 UTC, fnesveda requested changes
Cool! Just one note for the `LATEST_PYTHON` constant

2023-10-18 14:08 UTC, fnesveda commented on .github/workflows/release-python-playwright.yaml
> +  LATEST_PYTHON: "3.12"
Let's keep 3.11 as `LATEST_PYTHON` for a while, I bet there are still a lot of libraries broken on 3.12.

2023-10-18 14:08 UTC, fnesveda commented on .github/workflows/release-python-playwright.yaml
> +  LATEST_PYTHON: "3.12"
`LATEST_PYTHON` is bad naming here, it should be called `DEFAULT_PYTHON`, as it denotes the Python version to which the `apify/actor-python` image without any tag will point to. It's called "latest" as it's the `latest` tag of the image.

2023-10-18 14:51 UTC, fnesveda approved these changes

2023-10-18 14:52 UTC, merged