Feature version tagging fro automation libraries
apify/apify-actor-docker pull request #31
Opened 2021-01-22 10:16 UTC by petrpatek

It would deserve refactor. However, I have zero ideas how to do it 🙄

2021-01-24 16:02 UTC, mnmkng requested changes
Thanks! I asked Lukáš and he says that there's no elegant way of doing this so let's keep the separate `if` branches for now. Maybe we'll come up with something later.

2021-01-24 16:02 UTC, mnmkng commented on .github/workflows/release.yml
> +        image-name: [node, node-puppeteer-chrome, node-phantomjs, node-playwright, node-playwright-chrome, node-playwright-firefox, node-playwright-webkit]
Please remove `phantomjs` builds

2021-01-24 16:02 UTC, mnmkng commented on .github/workflows/release.yml
> +        image-name: [node-puppeteer-chrome-xvfb]
Lets not build a separate XVFB image for the new named images.

2021-01-24 16:02 UTC, mnmkng commented on .github/workflows/release.yml
> +        run: docker run apify/actor-${{ matrix.image-name }}:${{ env.PLAYWRIGHT_VERSION }}
Do we need to really test images with both tags? Could we just confirm that they are the same with some simple script, like comparing docker digests?

2021-01-24 16:10 UTC, mnmkng commented
Oh and two more things @petrpatek 

1. Let's keep the folders of the original images (basic, node-chrome and so on) for reference. At least for now.
2. Please remove Puppeteer from the `node-playwright` image in line with: https://sdk.apify.com/docs/next/guides/docker-images I will make it a bit smaller.

2021-01-25 10:55 UTC, petrpatek commented on .github/workflows/release.yml
> +        run: docker run apify/actor-${{ matrix.image-name }}:${{ env.PLAYWRIGHT_VERSION }}
I am afraid that the digests are created with the config file too so if the tag is different then the hash is different too. https://windsock.io/explaining-docker-image-ids/.

2021-01-25 18:12 UTC, mnmkng approved these changes

2021-01-25 18:12 UTC, merged