feat: add python playwright image
apify/apify-actor-docker pull request #92
Opened 2023-02-27 14:35 UTC by drobnikj

2023-02-28 13:24 UTC, fnesveda requested changes
Looks great! Just one comment about the publishing workflow

2023-02-28 13:24 UTC, fnesveda commented on python-playwright/src/main.py
> +    async with async_playwright() as playwright:
Can you add something like `print('Testing Docker image')` here? It's pretty useful in the other images, it saved me a few times when I forgot to copy over the source files in my actors.

2023-02-28 13:24 UTC, fnesveda commented on README.md
> +For image `apify/actor-node`, create folder `name`.
```suggestion
For image `apify/actor-node`, create folder `node`.
```

2023-02-28 13:24 UTC, fnesveda commented on .github/workflows/release-python-playwright.yml
> +        run: docker push apify/actor-${{ matrix.image-name }} --all-tags
You should run these steps only when the event is not `pull_request`, same as it is in the Node workflows

2023-03-01 10:05 UTC, jirimoravcik requested changes

2023-03-01 10:05 UTC, jirimoravcik commented on python-playwright/Dockerfile
> +ARG PLAYWRIGHT_VERSION=1.30.0
Why do you define this twice? I also see it on line 2

2023-03-01 10:05 UTC, jirimoravcik commented on python-playwright/Dockerfile
> +# Uncoment this line if you want to run browser in headfull mode by defautl.
```suggestion
# Uncomment this line if you want to run browser in headfull mode by default.
```

2023-03-01 10:05 UTC, jirimoravcik commented on python-playwright/src/main.py
> +            await run_test(launcher, headless=False)
add newline at the end of the file pls

2023-03-01 15:01 UTC, jirimoravcik commented on .github/workflows/release-python-playwright.yml
> +name: Release python playwright images
rename this to `.yaml`

2023-03-02 09:58 UTC, drobnikj commented on python-playwright/Dockerfile
> +ARG PLAYWRIGHT_VERSION=1.30.0
you need to have AVG before the docker step you want to use it, but I put the default version into env.

2023-03-02 10:11 UTC, drobnikj commented on python-playwright/Dockerfile
> +ARG PLAYWRIGHT_VERSION=1.30.0
It is by design https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact, you need to define it as the default  value it not there after FROM statement.

2023-03-03 09:14 UTC, jirimoravcik approved these changes

2023-03-03 17:51 UTC, fnesveda approved these changes

2023-03-06 08:15 UTC, merged